### PR TITLE
multi-objective evolution

### PR DESCRIPTION
**Pull request by OhadSharet**
multi-objective evolution added

### CODE REVIEW

**Comment by itaitzruia4** [comment]
- PEP8: Fix missing whitespaces after commas (for example, change `super().__init__(events,fitness_type)` into `super().__init__(events, fitness_type)` in SimpleVectorCreator, line 16). You can test your linting using flake8 (there's also a workflow for it)
- Rename `_calc_fronts_crowdnig` to `_calc_fronts_crowding` in `moe_front_sorting.py`
- What about different min/max directions? Currently, it seems like all objective functions are either minimization or maximization since `higher_is_better` is a boolean.
- Rename Problem1 to something more meaningful
- Rename `prob1MOAEvaluator` to `Prob1MOEEvaluator` (or a more meaningful name) in `test_problem1_eval.py`
- Why did you change `population_size` from 300 to 301 in `OneMaxProblem`?
- Remove commented-out code (bad tests in `test_problem1_eval.py`
- I didn't understand the comment in `test_moe_front_selection.py`, is this a reminder for you or advice for us? :)

**Review by zahidirfan — COMMENTED** [review]
While the code is finding Pareto fronts via sorting. I dont see the name of the file corresponding with its functionality. Moreover moe_front_sorting.py (translates into multi object evolution front sorting) does not make any sense? it should either be moga_front_sorting (since we are trying to build the NSGA) right?

**Comment by OhadSharet** [comment]
2nd pull request after fixing the following bugs 

PEP8: Fix missing whitespaces after commas (for example, change super().__init__(events,fitness_type) into super().__init__(events, fitness_type) in SimpleVectorCreator, line 16). You can test your linting using flake8 (there's also a workflow for it)
Rename _calc_fronts_crowdnig to _calc_fronts_crowding in moe_front_sorting.py
What about different min/max directions? Currently, it seems like all objective functions are either minimization or maximization since higher_is_better is a boolean.
Rename Problem1 to something more meaningful
Rename prob1MOAEvaluator to Prob1MOEEvaluator (or a more meaningful name) in test_problem1_eval.py
Why did you change population_size from 300 to 301 in OneMaxProblem?
Remove commented-out code (bad tests in test_problem1_eval.py
I didn't understand the comment in test_moe_front_selection.py

and changing "moe_front_sorting" to "moga_front_sorting"

**Comment by OhadSharet** [comment]
הי איתי תודה רבה על הCR והטיפים לאיך לתפוס עוד בעיות PEP8
שיניתי את כל הבעיות שהצבעת עליהן
את הנקודה השלישית (הנוגעת לכך שhigher_is_better צריך להיות מערך ולא
boolean  ) פתרתי כבר,
נכון לעכשיו אתה יכול לשלוח למחלקה מערך של boolean ואם אתה שולח לה boolean
בודד אז היא הופכת אותו למערך בפעולה הבונה שלה.

בתור defult argument  החלטתי שהפעולה הבונה של המחלקה עדיין תקבל boolean
בודד , מכיוון שאלה רוב השימושים שנתקלתי בהם (לפחות ב NSGA2 )
אבל אחרי שהקוד שלי יכנס לחבילה אוסיף מדריך שמסביר גם על כך שאפשר לשלוח
רשימה .



‫בתאריך יום א׳, 5 בפבר׳ 2023 ב-21:35 מאת ‪Itai Tzruia‬‏ <‪
***@***.***‬‏>:‬

**Pull request merged**
