### PR TITLE
added `update_parents` flag and set default values for `arity` in selection operators

### PR DESCRIPTION
**Pull request by itaitzruia4**
For memory efficiency, `Individual` now has a field `update_parents` to only update parents optionally.

### CODE REVIEW

**Comment by itaitzruia4** [comment]
should be merged after run-examples workflow is also checked

**Comment by achiyae** [comment]
@itaitzruia4 I don't like this PR. By its name, it seems like it's only adding a flag, but there are 53 file changes!
Also, when I look at the changes, it's doing way more than adding a flag...

**Comment by itaitzruia4** [comment]
Re-opening to run examples workflow too

**Comment by itaitzruia4** [comment]
> @itaitzruia4 I don't like this PR. By its name, it seems like it's only adding a flag, but there are 53 file changes! Also, when I look at the changes, it's doing way more than adding a flag...

It's been a while since I wrote this code, but it looks like most of the changes are due to format fixes.
The actual changes are update_parents flag (which requires a change in many files as you mentioned), and setting a default value for `arity` field in Selection operators (number of individuals to be selected).

**Comment by itaitzruia4** [comment]
Closing for now, I'll reimplement this feature and open a new PR

**Pull request closed without merging**
